cmake_minimum_required(VERSION 3.24)
if(NOT DEFINED ISOLATION_MODULE OR NOT DEFINED TEST_ROOT)
    message(FATAL_ERROR "ISOLATION_MODULE and TEST_ROOT are required")
endif()
set(case_count 0)
function(check_case name reject body)
    # Keep cache paths compact: Visual Studio's VCTargetsPath probe adds a long
    # .tlog suffix even for a configure-only NONE project on Windows.
    set(case_dir "${TEST_ROOT}/${case_count}")
    set(source_dir "${case_dir}/s")
    file(MAKE_DIRECTORY "${source_dir}")
    file(WRITE "${source_dir}/CMakeLists.txt"
        "cmake_minimum_required(VERSION 3.24)\nproject(calibration_view_isolation NONE)\n"
        "include([==[${ISOLATION_MODULE}]==])\n"
        "add_library(subject INTERFACE)\nadd_library(bridge INTERFACE)\n"
        "a0_defer_to_end_of_configure(a0_assert_no_calibration_view_dependency subject)\n${body}\n")
    execute_process(COMMAND "${CMAKE_COMMAND}" -S "${source_dir}" -B "${case_dir}/b"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE errors)
    if(reject)
        if(result EQUAL 0 OR NOT "${output}${errors}" MATCHES "must not (link|compile)")
            message(FATAL_ERROR "${name}: rejection was not the dependency policy (${result})")
        endif()
    elseif(NOT result EQUAL 0)
        message(FATAL_ERROR "${name}: pure numerical target rejected (${result})")
    endif()
    math(EXPR count "${case_count} + 1")
    set(case_count ${count} PARENT_SCOPE)
endfunction()
check_case(pure_allowed FALSE "target_link_libraries(subject INTERFACE bridge)\nset_property(TARGET bridge PROPERTY INTERFACE_SOURCES src/m2/calibration_view_geometry.cpp)")
foreach(library ole32 windowscodecs bcrypt shell32 a0_m2_render a0_m2_offline_stitcher a0_m2_synthetic_pair a0_m2_rig_profile_v2 opencv_core opencv_calib3d opencv_world4120 cv2)
    check_case("direct_${library}" TRUE "target_link_libraries(subject INTERFACE ${library})")
    check_case("transitive_${library}" TRUE "target_link_libraries(subject INTERFACE bridge)\ntarget_link_libraries(bridge INTERFACE $<$<CONFIG:Release>:${library}>)")
endforeach()
check_case(imported_opencv TRUE "add_library(OpenCV::Core INTERFACE IMPORTED)\ntarget_link_libraries(subject INTERFACE OpenCV::Core)")
check_case(versioned_defaultlib TRUE "target_link_libraries(subject INTERFACE bridge)\ntarget_link_options(bridge INTERFACE /DEFAULTLIB:opencv_calib3d4120.lib)")
check_case(unix_versioned_library TRUE "target_link_libraries(subject INTERFACE -lopencv_core4120)")
check_case(archive_filename TRUE "target_link_libraries(subject INTERFACE C:/deps/libopencv_core.a)")
check_case(shared_versioned_filename TRUE "target_link_libraries(subject INTERFACE bridge)\ntarget_link_libraries(bridge INTERFACE C:/deps/libopencv_core.so.4120)")
check_case(mixed_case_versioned TRUE "target_link_options(subject INTERFACE /DEFAULTLIB:OpenCV_World4120.lib)")
foreach(source opencv/calib3d.cpp render.cpp document_render.cpp offline_stitcher.cpp synthetic_pair_geometry.cpp rig_profile_v2.cpp)
    string(REPLACE "/" "_" name "${source}")
    check_case("source_${name}" TRUE "set_property(TARGET subject PROPERTY INTERFACE_SOURCES src/m2/${source})")
endforeach()
message(STATUS "Calibration view isolation: ${case_count} cases passed")
