# Fails configuration when `target`, or anything it links (through
# LINK_LIBRARIES or INTERFACE_LINK_LIBRARIES, transitively), names one of the
# forbidden system libraries. Used to keep pure-computation libraries free of
# Win32 / COM / WIC / BCrypt dependencies.
function(a0_assert_no_link_dependency target)
    set(forbidden ole32 windowscodecs bcrypt)
    set(pending "${target}")
    set(seen "")
    while(pending)
        list(POP_FRONT pending current)
        if(current IN_LIST seen)
            continue()
        endif()
        list(APPEND seen "${current}")
        string(REGEX REPLACE "^\\$<LINK_ONLY:(.*)>$" "\\1" name "${current}")
        string(TOLOWER "${name}" lowered)
        string(REGEX REPLACE "\\.lib$" "" lowered "${lowered}")
        if(lowered IN_LIST forbidden)
            message(FATAL_ERROR "${target} must not link ${name} (reached through its link dependencies)")
        endif()
        if(TARGET "${name}")
            foreach(property LINK_LIBRARIES INTERFACE_LINK_LIBRARIES)
                get_target_property(dependencies "${name}" ${property})
                if(dependencies)
                    list(APPEND pending ${dependencies})
                endif()
            endforeach()
        endif()
    endwhile()
endfunction()