using System.Globalization;
using System.Text.Json;

namespace A0CameraStitcher.M3.Foundation.Hardware;

/// <summary>
/// In-process simulated <c>a0.camera-agent.hardware-dual-binding.v1</c> agent.
/// </summary>
/// <remarks>
/// <para>
/// This exists because the M3 simulated lane has to show the binding screen with no camera, no SDK
/// and no Agent process at all -- the same reason <c>SimulatedCameraAgent</c> exists for the
/// simulated capture protocol. It is also what the binding UI tests drive.
/// </para>
/// <para>
/// It is a second implementation of rules the native agent already implements, and that is a real
/// cost worth naming: nothing here proves the two agree. What this class is responsible for is the
/// wire contract -- the same operations, the same result codes, the same payload field names -- so
/// that a UI built against it is built against the shape the hardware agent actually produces.
/// Proving the two implementations agree needs a conformance test that runs both, which needs the
/// Native lane and is deliberately out of this Issue's scope.
/// </para>
/// <para>
/// It performs no capture, opens no camera, reads no card, and writes nothing. The "preview" is
/// generated bytes.
/// </para>
/// </remarks>
public sealed class SimulatedDualBindingAgent
{
    private readonly SimulatedDualBindingOptions _options;
    private readonly List<Candidate> _candidates = [];
    private DualBindingInvalidationReason _pendingInvalidation;
    private DualBindingInvalidationReason _invalidationReason;
    private DualBindingSessionState _state = DualBindingSessionState.None;
    private string _sessionId = string.Empty;
    private int? _activeLiveViewOrdinal;
    private int _sessionCounter;
    private bool _enumerationInvalidationArmed;
    private bool _captureHostActivated;

    public SimulatedDualBindingAgent(SimulatedDualBindingOptions? options = null)
    {
        _options = options ?? new SimulatedDualBindingOptions();
        _pendingInvalidation = _options.PendingInvalidation;
        _enumerationInvalidationArmed =
            _options.InvalidationDuringEnumeration != DualBindingInvalidationReason.None;
    }

    public DualBindingSessionState State => _state;

    public int EnumerationCount { get; private set; }

    public int ActiveLiveViewCount => _candidates.Count(candidate => candidate.LiveViewActive);

    /// <summary>Non-zero would mean the client let two Live Views overlap.</summary>
    public int ConcurrentLiveViewViolationCount { get; private set; }

    public int EndBindingSessionCount { get; private set; }

    public bool CaptureHostActivated => _captureHostActivated;

    /// <summary>
    /// Raises a typed invalidation, as an Agent restart, USB reconnect, topology change, SDK
    /// manager recreation or SDK error would. Reported by the next session-scoped operation.
    /// </summary>
    public void RaiseInvalidation(DualBindingInvalidationReason reason) => _pendingInvalidation = reason;

    public string Handle(string requestJson)
    {
        string requestId;
        string operation;
        JsonElement payload;
        JsonDocument document;
        try
        {
            document = JsonDocument.Parse(requestJson, new JsonDocumentOptions
            {
                AllowTrailingCommas = false,
                CommentHandling = JsonCommentHandling.Disallow,
                MaxDepth = 32,
            });
        }
        catch (JsonException)
        {
            return Rejection("rejected", "MalformedEnvelope", "The binding request is malformed.");
        }

        using (document)
        {
            var root = document.RootElement;
            requestId = root.TryGetProperty("requestId", out var id) && id.ValueKind == JsonValueKind.String
                ? id.GetString() ?? "rejected"
                : "rejected";
            if (!IsBindingEnvelope(root))
            {
                return Rejection(
                    requestId,
                    "DualBindingProtocolRequired",
                    "The request is not the required Dual binding v1 protocol.");
            }

            operation = root.TryGetProperty("operation", out var op) && op.ValueKind == JsonValueKind.String
                ? op.GetString() ?? string.Empty
                : string.Empty;
            if (!root.TryGetProperty("payload", out payload) || payload.ValueKind != JsonValueKind.Object)
            {
                return Rejection(requestId, "InvalidPayload", "The binding payload must be an object.");
            }

            if (operation == DualBindingCameraAgentProtocol.Operations.BeginBinding)
            {
                return BeginBinding(requestId);
            }

            if (!DualBindingCameraAgentProtocol.Operations.Required.Contains(operation, StringComparer.Ordinal))
            {
                return Rejection(requestId, "UnsupportedOperation", "The binding operation is unsupported.");
            }

            // Session identity is compared before the pending invalidation is consumed, so a stale
            // request can neither learn this session's state nor swallow the event the live
            // session's next request needs to see.
            var sessionId = payload.TryGetProperty("sessionId", out var session) &&
                session.ValueKind == JsonValueKind.String
                    ? session.GetString() ?? string.Empty
                    : string.Empty;
            if (_sessionId.Length == 0 || !string.Equals(sessionId, _sessionId, StringComparison.Ordinal))
            {
                return Rejection(
                    requestId,
                    "SessionMismatch",
                    "The named binding session is not the one this agent is serving.");
            }

            if (operation == DualBindingCameraAgentProtocol.Operations.CancelBinding)
            {
                return CancelBinding(requestId);
            }

            if (_pendingInvalidation != DualBindingInvalidationReason.None)
            {
                Invalidate(_pendingInvalidation);
                _pendingInvalidation = DualBindingInvalidationReason.None;
            }

            if (_state == DualBindingSessionState.Invalid)
            {
                return InvalidatedRejection(requestId);
            }

            return operation switch
            {
                DualBindingCameraAgentProtocol.Operations.StartCandidateLiveView =>
                    StartLiveView(requestId, payload),
                DualBindingCameraAgentProtocol.Operations.GetCandidateLiveViewFrame =>
                    GetFrame(requestId, payload),
                DualBindingCameraAgentProtocol.Operations.ConfirmAlias =>
                    ConfirmAlias(requestId, payload),
                DualBindingCameraAgentProtocol.Operations.CompleteBinding =>
                    CompleteBinding(requestId),
                DualBindingCameraAgentProtocol.Operations.ActivateCapture =>
                    ActivateCapture(requestId),
                _ => Rejection(requestId, "UnsupportedOperation", "The binding operation is unsupported."),
            };
        }
    }

    private string BeginBinding(string requestId)
    {
        // Discard the previous session before anything can fail, so a refused begin-binding cannot
        // leave an older session addressable.
        _sessionId = string.Empty;
        _activeLiveViewOrdinal = null;
        _invalidationReason = DualBindingInvalidationReason.None;
        _state = DualBindingSessionState.None;
        _captureHostActivated = false;
        _candidates.Clear();

        // Drain whatever was queued for the session just discarded. Acting on it would refuse the
        // replacement session for something that happened before it existed.
        _pendingInvalidation = DualBindingInvalidationReason.None;

        EnumerationCount++;
        var tokens = new List<string>();
        for (var ordinal = 0; ordinal < _options.CandidateCount; ordinal++)
        {
            tokens.Add(_options.SourceObjectTokenStyle switch
            {
                SimulatedSourceObjectTokenStyle.Empty => string.Empty,
                SimulatedSourceObjectTokenStyle.Duplicate => "simulated-source-object-shared",
                _ => $"simulated-source-object-{EnumerationCount}-{ordinal}",
            });
        }

        if (_enumerationInvalidationArmed)
        {
            _pendingInvalidation = _options.InvalidationDuringEnumeration;
            // One shot, so the operator's retry can succeed.
            _enumerationInvalidationArmed = false;
        }

        if (tokens.Count != DualBindingCameraAgentProtocol.RequiredCandidateCount)
        {
            return Rejection(
                requestId,
                "CandidateCountNotTwo",
                $"Exactly two candidates are required; {tokens.Count} were enumerated.");
        }

        if (tokens.Any(string.IsNullOrEmpty))
        {
            return Rejection(
                requestId,
                "CandidateSourceObjectMissing",
                "A candidate carries no source object.");
        }

        if (tokens.Distinct(StringComparer.Ordinal).Count() != tokens.Count)
        {
            return Rejection(
                requestId,
                "DuplicateCandidateSourceObject",
                "Two candidates share one source object.");
        }

        if (_pendingInvalidation != DualBindingInvalidationReason.None)
        {
            // Observed during or after enumeration, so the candidates just collected may already be
            // stale. Fail closed and let the retry start clean.
            var reason = _pendingInvalidation;
            _pendingInvalidation = DualBindingInvalidationReason.None;
            Invalidate(reason);
            return Rejection(
                requestId,
                "BindingInvalidated",
                $"The SDK reported {reason} while candidates were being collected.");
        }

        for (var ordinal = 0; ordinal < tokens.Count; ordinal++)
        {
            _candidates.Add(new Candidate { Ordinal = ordinal, SourceObjectToken = tokens[ordinal] });
        }

        _sessionCounter++;
        _sessionId = BuildSessionId(_sessionCounter);
        _state = DualBindingSessionState.CollectingCandidates;

        return Success(requestId, "BindingSessionStarted", writer =>
        {
            writer.WriteString("sessionId", _sessionId);
            writer.WriteString("state", _state.ToString());
            writer.WriteStartArray("candidateOrdinals");
            foreach (var candidate in _candidates)
            {
                writer.WriteNumberValue(candidate.Ordinal);
            }

            writer.WriteEndArray();
        });
    }

    private string StartLiveView(string requestId, JsonElement payload)
    {
        if (_state != DualBindingSessionState.CollectingCandidates)
        {
            return Rejection(
                requestId,
                "BindingNotCollecting",
                "Live View is only offered while candidates are still being assigned.");
        }

        if (!TryReadOrdinal(payload, out var ordinal) || FindCandidate(ordinal) is not { } candidate)
        {
            return Rejection(
                requestId,
                "UnknownCandidateOrdinal",
                "The candidate ordinal is not part of this binding session.");
        }

        if (candidate.CameraAlias.Length > 0)
        {
            return Rejection(
                requestId,
                "CandidateAlreadyAssigned",
                "This candidate was already assigned and its session closed.");
        }

        if (_activeLiveViewOrdinal is { } active && active != ordinal)
        {
            // Switching bodies is normal; two running at once never is. If the stop fails, the new
            // one does not start.
            if (_options.FailStopLiveView)
            {
                Invalidate(DualBindingInvalidationReason.SdkError);
                return Rejection(
                    requestId,
                    "LiveViewStopFailed",
                    "The previously running Live View could not be stopped.");
            }

            FindCandidate(active)!.LiveViewActive = false;
            _activeLiveViewOrdinal = null;
        }

        if (_activeLiveViewOrdinal is null)
        {
            if (_options.FailStartLiveView)
            {
                return Rejection(
                    requestId,
                    "LiveViewStartFailed",
                    "The SDK refused to start Live View for this candidate.");
            }

            if (ActiveLiveViewCount > 0)
            {
                ConcurrentLiveViewViolationCount++;
            }

            candidate.LiveViewActive = true;
            _activeLiveViewOrdinal = ordinal;
        }

        return Success(requestId, "CandidateLiveViewStarted", writer =>
        {
            writer.WriteString("sessionId", _sessionId);
            writer.WriteNumber("candidateOrdinal", ordinal);
            writer.WriteBoolean("liveViewActive", true);
        });
    }

    private string GetFrame(string requestId, JsonElement payload)
    {
        if (!TryReadOrdinal(payload, out var ordinal) || _activeLiveViewOrdinal != ordinal)
        {
            return Rejection(requestId, "LiveViewNotActive", "No Live View is running for this candidate.");
        }

        if (_options.LiveViewFrameBytes == 0)
        {
            return Rejection(requestId, "LiveViewFrameUnavailable", "The SDK returned no Live View frame.");
        }

        if (_options.LiveViewFrameBytes > DualBindingCameraAgentProtocol.MaximumLiveViewFrameBytes)
        {
            // Refused, never truncated: the operator decides which body they are looking at from
            // this image, and half an image is a wrong answer waiting to happen.
            return Rejection(
                requestId,
                "LiveViewFrameTooLarge",
                "The Live View frame exceeds the bounded preview size.");
        }

        var frame = new byte[_options.LiveViewFrameBytes];
        for (var index = 0; index < frame.Length; index++)
        {
            frame[index] = (byte)((index + ordinal) & 0xFF);
        }

        return Success(requestId, "CandidateLiveViewFrame", writer =>
        {
            writer.WriteString("sessionId", _sessionId);
            writer.WriteNumber("candidateOrdinal", ordinal);
            writer.WriteNumber("frameBytes", frame.Length);
            writer.WriteString("frameBase64", Convert.ToBase64String(frame));
        });
    }

    private string ConfirmAlias(string requestId, JsonElement payload)
    {
        if (_state != DualBindingSessionState.CollectingCandidates)
        {
            return Rejection(
                requestId,
                "BindingNotCollecting",
                "Aliases are only assigned while candidates are being collected.");
        }

        if (!TryReadOrdinal(payload, out var ordinal) || FindCandidate(ordinal) is not { } candidate)
        {
            return Rejection(
                requestId,
                "UnknownCandidateOrdinal",
                "The candidate ordinal is not part of this binding session.");
        }

        var alias = payload.TryGetProperty("cameraAlias", out var value) && value.ValueKind == JsonValueKind.String
            ? value.GetString() ?? string.Empty
            : string.Empty;
        if (!DualBindingCameraAgentProtocol.OrderedAliases.Contains(alias, StringComparer.Ordinal))
        {
            return Rejection(requestId, "UnknownCameraAlias", "The rig defines only CAM-A and CAM-B.");
        }

        // Re-using a candidate or an alias is refused rather than overwritten: an operator who
        // assigned the same body twice has misread the Live View, and taking the second answer
        // silently would hide that.
        if (candidate.CameraAlias.Length > 0)
        {
            return Rejection(
                requestId,
                "CandidateAlreadyAssigned",
                "One candidate cannot be assigned to both aliases.");
        }

        if (_candidates.Any(other => string.Equals(other.CameraAlias, alias, StringComparison.Ordinal)))
        {
            return Rejection(requestId, "AliasAlreadyAssigned", $"{alias} was already assigned.");
        }

        candidate.CameraAlias = alias;

        var liveViewStopped = !_options.FailStopLiveView;
        var sdkSessionClosed = !_options.FailCloseCandidateSession;
        if (liveViewStopped)
        {
            candidate.LiveViewActive = false;
            if (_activeLiveViewOrdinal == ordinal)
            {
                _activeLiveViewOrdinal = null;
            }
        }

        candidate.LiveViewStopped = liveViewStopped;
        candidate.SdkSessionClosed = sdkSessionClosed;
        if (_candidates.All(other => other.CameraAlias.Length > 0))
        {
            _state = DualBindingSessionState.AwaitingQuiesce;
        }

        if (!liveViewStopped || !sdkSessionClosed)
        {
            return Rejection(requestId, "QuiesceIncomplete", "The candidate did not quiesce.", writer =>
            {
                writer.WriteString("sessionId", _sessionId);
                writer.WriteNumber("candidateOrdinal", ordinal);
                writer.WriteBoolean("liveViewStopped", liveViewStopped);
                writer.WriteBoolean("sdkSessionClosed", sdkSessionClosed);
                writer.WriteString("state", _state.ToString());
            });
        }

        return Success(requestId, "CandidateAliasConfirmed", writer =>
        {
            writer.WriteString("sessionId", _sessionId);
            writer.WriteNumber("candidateOrdinal", ordinal);
            writer.WriteString("cameraAlias", alias);
            writer.WriteString("state", _state.ToString());
        });
    }

    private string CompleteBinding(string requestId)
    {
        if (_state == DualBindingSessionState.Ready)
        {
            return Rejection(requestId, "BindingAlreadyComplete", "The binding is already complete.");
        }

        if (_candidates.Count != DualBindingCameraAgentProtocol.RequiredCandidateCount ||
            !DualBindingCameraAgentProtocol.OrderedAliases.All(alias =>
                _candidates.Any(candidate => string.Equals(candidate.CameraAlias, alias, StringComparison.Ordinal))))
        {
            return Rejection(
                requestId,
                "AliasAssignmentIncomplete",
                "Both CAM-A and CAM-B must be assigned before a binding completes.");
        }

        // The quiesce the candidates actually reported, not an optimistic one. This is what keeps a
        // still-streaming or still-open body out of a completed binding.
        if (_candidates.Any(candidate => !candidate.LiveViewStopped || !candidate.SdkSessionClosed))
        {
            return Rejection(
                requestId,
                "CandidateNotQuiesced",
                "Every candidate's Live View must be stopped and its SDK session closed.");
        }

        _state = DualBindingSessionState.Ready;
        var confirmedAtUtc = _options.ConfirmedAtUtc.ToString("yyyy-MM-ddTHH:mm:ssZ", CultureInfo.InvariantCulture);
        return Success(requestId, "BindingCompleted", writer =>
        {
            writer.WriteString("sessionId", _sessionId);
            writer.WriteString("state", _state.ToString());
            writer.WriteStartArray("evidence");
            foreach (var alias in DualBindingCameraAgentProtocol.OrderedAliases)
            {
                writer.WriteStartObject();
                writer.WriteString("cameraAlias", alias);
                writer.WriteString("providerId", "a0.dual-identity.session-binding");
                writer.WriteNumber("providerVersion", 1);
                writer.WriteString("confirmedAtUtc", confirmedAtUtc);
                writer.WriteString("invalidationReason", DualBindingInvalidationReason.None.ToString());
                writer.WriteEndObject();
            }

            writer.WriteEndArray();
        });
    }

    private string ActivateCapture(string requestId)
    {
        if (_state != DualBindingSessionState.Ready)
        {
            return Rejection(
                requestId,
                "BindingNotReady",
                "Capture activation requires a completed Ready binding.");
        }

        _captureHostActivated = true;
        return Success(requestId, "CaptureHostActivated", writer =>
        {
            writer.WriteString("sessionId", _sessionId);
            writer.WriteString("state", DualBindingSessionState.Ready.ToString());
            writer.WriteBoolean("captureHostActivated", true);
        });
    }

    private string CancelBinding(string requestId)
    {
        EndBindingSessionCount++;
        var cancelledSession = _sessionId;
        if (_options.FailEndBindingSession)
        {
            Invalidate(DualBindingInvalidationReason.SdkError);
            return Rejection(requestId, "BindingCleanupFailed", "Binding SDK cleanup could not be confirmed.", writer =>
            {
                writer.WriteString("sessionId", cancelledSession);
                writer.WriteString("state", DualBindingSessionState.Invalid.ToString());
                writer.WriteString("invalidationReason", _invalidationReason.ToString());
                writer.WriteString("detail", "Binding SDK cleanup could not be confirmed.");
            });
        }

        foreach (var candidate in _candidates)
        {
            candidate.LiveViewActive = false;
            candidate.LiveViewStopped = true;
            candidate.SdkSessionClosed = true;
        }
        _activeLiveViewOrdinal = null;
        _state = DualBindingSessionState.None;
        _sessionId = string.Empty;
        _captureHostActivated = false;
        _candidates.Clear();
        return Success(requestId, "BindingCancelled", writer =>
        {
            writer.WriteString("sessionId", cancelledSession);
            writer.WriteString("state", DualBindingSessionState.None.ToString());
            writer.WriteBoolean("liveViewStopped", true);
            writer.WriteBoolean("sdkSessionClosed", true);
            writer.WriteBoolean("sdkSessionEnded", true);
        });
    }

    private void Invalidate(DualBindingInvalidationReason reason)
    {
        _state = DualBindingSessionState.Invalid;
        if (_invalidationReason == DualBindingInvalidationReason.None)
        {
            // First reason wins: it is the one that explains why the binding stopped being
            // trustworthy.
            _invalidationReason = reason;
        }

        foreach (var candidate in _candidates)
        {
            candidate.LiveViewActive = false;
        }

        _activeLiveViewOrdinal = null;
    }

    private Candidate? FindCandidate(int ordinal) =>
        _candidates.FirstOrDefault(candidate => candidate.Ordinal == ordinal);

    private static bool TryReadOrdinal(JsonElement payload, out int ordinal)
    {
        ordinal = -1;
        return payload.TryGetProperty("candidateOrdinal", out var value) &&
            value.ValueKind == JsonValueKind.Number &&
            value.TryGetInt32(out ordinal);
    }

    private static bool IsBindingEnvelope(JsonElement root) =>
        root.ValueKind == JsonValueKind.Object &&
        root.TryGetProperty("schemaVersion", out var schema) &&
        schema.ValueKind == JsonValueKind.String &&
        schema.GetString() == DualBindingCameraAgentProtocol.SchemaVersion &&
        root.TryGetProperty("marker", out var marker) &&
        marker.ValueKind == JsonValueKind.String &&
        marker.GetString() == DualBindingCameraAgentProtocol.Marker &&
        root.TryGetProperty("simulation", out var simulation) &&
        simulation.ValueKind == JsonValueKind.False;

    // Shaped exactly like the hardware agent's: 32 hex characters, never all zero. The value is a
    // correlation token, not a capability, so a fixed simulated prefix is fine -- what matters is
    // that a new session never reproduces an old one's id, which the counter guarantees.
    private const string SimulatedSessionPrefix = "5124b15124b15124b15124b1";

    private static string BuildSessionId(int counter) => SimulatedSessionPrefix + counter.ToString("x8");

    private string InvalidatedRejection(string requestId) =>
        Rejection(requestId, "BindingInvalidated", "The binding session is no longer trustworthy.", writer =>
        {
            writer.WriteString("sessionId", _sessionId);
            writer.WriteString("state", DualBindingSessionState.Invalid.ToString());
            writer.WriteString("invalidationReason", _invalidationReason.ToString());
        });

    private static string Success(string requestId, string resultCode, Action<Utf8JsonWriter> writePayload) =>
        Envelope(requestId, true, resultCode, writePayload);

    private static string Rejection(
        string requestId,
        string resultCode,
        string detail,
        Action<Utf8JsonWriter>? writePayload = null) =>
        Envelope(
            requestId,
            false,
            resultCode,
            writePayload ?? (writer => writer.WriteString("detail", detail)));

    private static string Envelope(
        string requestId,
        bool success,
        string resultCode,
        Action<Utf8JsonWriter> writePayload)
    {
        using var buffer = new MemoryStream();
        using (var writer = new Utf8JsonWriter(buffer))
        {
            writer.WriteStartObject();
            writer.WriteString("schemaVersion", DualBindingCameraAgentProtocol.SchemaVersion);
            writer.WriteBoolean("simulation", false);
            writer.WriteString("marker", DualBindingCameraAgentProtocol.Marker);
            writer.WriteString("requestId", requestId);
            writer.WriteBoolean("success", success);
            writer.WriteString("resultCode", resultCode);
            writer.WritePropertyName("payload");
            writer.WriteStartObject();
            writePayload(writer);
            writer.WriteEndObject();
            writer.WriteEndObject();
        }

        return System.Text.Encoding.UTF8.GetString(buffer.ToArray());
    }

    private sealed class Candidate
    {
        public required int Ordinal { get; init; }
        public required string SourceObjectToken { get; init; }
        public string CameraAlias { get; set; } = string.Empty;
        public bool LiveViewActive { get; set; }
        public bool LiveViewStopped { get; set; }
        public bool SdkSessionClosed { get; set; }
    }
}

public enum SimulatedSourceObjectTokenStyle
{
    Distinct,
    Duplicate,
    Empty,
}

/// <summary>
/// How the simulated agent should behave. Every knob exists because some required rejection path
/// needs it; there is no "make it work" switch.
/// </summary>
public sealed record SimulatedDualBindingOptions
{
    public int CandidateCount { get; init; } = DualBindingCameraAgentProtocol.RequiredCandidateCount;
    public SimulatedSourceObjectTokenStyle SourceObjectTokenStyle { get; init; } =
        SimulatedSourceObjectTokenStyle.Distinct;
    public bool FailStartLiveView { get; init; }
    public bool FailStopLiveView { get; init; }
    public bool FailCloseCandidateSession { get; init; }
    public bool FailEndBindingSession { get; init; }
    public int LiveViewFrameBytes { get; init; } = 4096;
    public DualBindingInvalidationReason PendingInvalidation { get; init; } = DualBindingInvalidationReason.None;
    public DualBindingInvalidationReason InvalidationDuringEnumeration { get; init; } =
        DualBindingInvalidationReason.None;
    public DateTimeOffset ConfirmedAtUtc { get; init; } = new(2026, 8, 21, 0, 0, 0, TimeSpan.Zero);
}

/// <summary>
/// Routes the binding protocol to an in-process <see cref="SimulatedDualBindingAgent"/>.
/// </summary>
/// <remarks>
/// No pipe is involved. The pipe layer -- framing, the 1 MiB bound, the delivery acknowledgment --
/// is contract-tested natively against the real host and is not what these tests are about.
/// </remarks>
public sealed class SimulatedDualBindingAgentTransport : IHardwareCameraAgentTransport
{
    private readonly SimulatedDualBindingAgent _agent;

    public SimulatedDualBindingAgentTransport(SimulatedDualBindingAgent agent) => _agent = agent;

    public Task<string> SendAsync(string requestJson, CancellationToken cancellationToken = default)
    {
        cancellationToken.ThrowIfCancellationRequested();
        return Task.FromResult(_agent.Handle(requestJson));
    }
}
